apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foo-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: foo-app-namespace
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/zilinjak/foo-app.git
    targetRevision: HEAD
    path: chart
