apiVersion: v1
kind: Service
metadata:
  name: argocd-service
  namespace: argocd
spec:
  selector:
    name: argocd-server
  ports:
    - name: argocd-server-port
      port: 6001
      targetPort: 8080
  type: LoadBalancer
