apiVersion: v1
kind: Service
metadata:
  name: argocd-service
  namespace: argocd
spec:
  selector:
    name: argocd-server
  ports:
    - name: argocd-server-port
      port: 6001
      targetPort: 8080
    - name: argocd-server-port-2
      port: 6002
      targetPort: 8083
  type: LoadBalancer
