apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bar-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: bar-app-namespace
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/zilinjak/foo-app.git
    targetRevision: HEAD
    path: chart
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
