apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: util-application-set
  namespace: argocd  
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: 'https://github.com/zilinjak/artemis-mq-kafka.git'  # Replace with your Git repository URL
      revision: HEAD
      directories:
      - path: "*"
  template:
    metadata:
      name: '{{path.basename}}-app'
      namespace: '{{path.basename}}'
    spec:
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      project: default
      source:
        repoURL: 'https://github.com/zilinjak/artemis-mq-kafka.git'  # Replace with your Git repository URL
        path: '{{path.path}}'
        targetRevision: HEAD
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
